services:
  wmts:
    restful: true
    kvp: false
    md:
      title: RBT WMTS
  wms:
    md:
      title: RBT WMS

layers:
  - name: rbt_topo_3857
    title: rbt_topo_3857
    sources: [rbt_topo_3857_cache]
  - name: rbt_dark_3857
    title: rbt_dark_3857
    sources: [rbt_dark_3857_cache]
  - name: rbt_overlay_3857
    title: rbt_overlay_3857
    sources: [rbt_overlay_3857_cache]

caches:
  rbt_topo_3857_cache:
    sources: [rbt_topo_source]
    format: mixed
    request_format: image/png
    minimize_meta_requests: true
    grids: [webmercator]
    cache:
      type: geopackage
      levels: true
      directory: /data/geopackage/topo3857
      table_name: topo_3857
  rbt_dark_3857_cache:
    sources: [rbt_dark_source]
    format: mixed
    request_format: image/png
    minimize_meta_requests: true
    grids: [webmercator]
    cache:
      type: geopackage
      levels: true
      directory: /data/geopackage/dark3857
      table_name: dark_3857
  rbt_overlay_3857_cache:
    sources: [rbt_overlay_source]
    format: mixed
    request_format: image/png
    minimize_meta_requests: true
    grids: [webmercator]
    cache:
      type: geopackage
      levels: true
      directory: /data/geopackage/overlay3857
      table_name: overlay_3857

sources:
  rbt_topo_source:
    type: tile
    # Local TileserverGL container, EPSG:3857 (Web Mercator)
    url: http://tileservergl:8080/styles/RBT-TOPO/%(z)s/%(x)s/%(y)s.png
    grid: webmercator
  rbt_dark_source:
    type: tile
    # Local TileserverGL container, EPSG:3857 (Web Mercator)
    url: http://tileservergl:8080/styles/RBT-DARK/%(z)s/%(x)s/%(y)s.png
    grid: webmercator
  rbt_overlay_source:
    type: tile
    # Local TileserverGL container, EPSG:3857 (Web Mercator)
    url: http://tileservergl:8080/styles/RBT-OVERLAY/%(z)s/%(x)s/%(y)s.png
    grid: webmercator
    transparent: true

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
    srs: EPSG:3857
    origin: nw
    tile_size: [256, 256]
    bbox:
      [
        -20037508.342789244,
        -20037508.342789244,
        20037508.342789244,
        20037508.342789244
      ]

globals:
  http:
    ssl_no_cert_checks: true
  image:
    resampling_method: bicubic
    paletted: false
  cache:
    base_dir: /data
    lock_dir: /locks
    tile_lock_dir: /tile_locks
    meta_size: [1, 1]
    concurrent_tile_creators: 8
    meta_buffer: 0
    bulk_meta_tiles: true
