apiVersion: v2
name: rbt
description: Umbrella Helm chart for deploying RBT (Releasable Basemap Tiles) stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: tileservergl
    version: "0.1.0"
    repository: "file://./tileservergl"
  - name: mapproxy
    version: "0.1.0"
    repository: "file://./mapproxy" 