# Global values
global:
  namespace: "" # Empty means use current namespace

# TileserverGL configuration
tileservergl:
  image: 'docker.io/mjj203/rbt:tileservergl-3395-latest'
  name: tileservergl
  network: tileserver
  replicas: 1
  config: '/data/config/config.json'
  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
      cpu: "4000m"

# MapProxy configuration
mapproxy:
  image: 'docker.io/mjj203/mapproxy:latest'
  name: mapproxy
  network: mapproxy
  replicas: 1
  tileserverService: "tileserver"
  nginx:
    image: 'docker.io/mjj203/nginx:latest'
    replicas: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m" 